// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyecwyzfegpfdmlvadoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5ZWN3eXpmZWdwZmRtbHZhZG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODUyNDUsImV4cCI6MjA2Njg2MTI0NX0.mNsMmPWbLy8LDdKPm8ugghQLPWwgmIS6ScUXP5xt5Vs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});